### ISSUE TITLE
Retiring the repository

### ISSUE THREAD

**Issue by nihil-admirari** [yt-dlp/FFmpeg-Builds#72]
@pukkandan, the last remaining FFmpeg patch was merged to FFmpeg master yesterday: https://github.com/FFmpeg/FFmpeg/commit/b76053d8bf322b197a9d07bd27bbdad14fd5bc15.

That patch is still applicable to 7.1 release, but there are no others. Once a new FFmpeg release is made, there'll be no point in having this repository.

If new patches are added, the repository can be resurrected.

**Comment by pukkandan** [comment]
Let me know when that happens. We can add a note to readme and archive the repo

PS: Thanks for everything you've done for this!

**Comment by gamer191** [comment]
> Once a new FFmpeg release is made, there'll be no point in having this repository.

Does FFmpeg 7.1.1 include the fix? (EDIT: If not, line 59 of the readme should probably be updated)

Thanks for everything you've done for this repo! If, and only if, you wish to continue to maintain this, I might go through the yt-dlp external issues list to see if there's any more patches that should be added to this repo (I've been meaning to do that for a while but I keep forgetting)?


EDIT: before archiving the repo, https://trac.ffmpeg.org/ticket/7673 should probably be added to "patches welcome"

**Comment by nihil-admirari** [comment]
> If not, line 59 of the readme should probably be updated

Fixed.

> EDIT: before archiving the repo, https://trac.ffmpeg.org/ticket/7673 should probably be added to "patches welcome"

Added.

**Comment by God-damnit-all** [comment]
Rather than archiving, it might be better to simply halt the workflows, remove the releases, and say the repo is retired. That way a PR can be submitted for the patches that are welcome, as well as allowing a new issue to be posted if there's something that was overlooked.

**Comment by gamer191** [comment]
> If new patches are added, the repository can be resurrected.

I intend to submit a bug report to FFmpeg and write a patch for https://github.com/yt-dlp/yt-dlp/issues/12495 very soon (probably tomorrow). So unfortunately I think this repo will need to stay for a little while longer

(I’m aware that the issue could be fixed by passing the -allowed_extensions CLI option to FFmpeg, but Bashonly and I have collectively decided against that, on the basis that maintaining a list of allowed_extensions to pass to FFmpeg is not sustainable, and potentially a security risk)

**Comment by God-damnit-all** [comment]
> > If new patches are added, the repository can be resurrected.
> 
> I intend to submit a bug report to FFmpeg and write a patch for [yt-dlp/yt-dlp#12495](https://github.com/yt-dlp/yt-dlp/issues/12495) very soon (probably tomorrow). So unfortunately I think this repo will need to stay for a little while longer
> 
> (I’m aware that the issue could be fixed by passing the -allowed_extensions CLI option to FFmpeg, but Bashonly and I have collectively decided against that, on the basis that maintaining a list of allowed_extensions to pass to FFmpeg is not sustainable, and potentially a security risk)

How's the progress on this coming?

**Comment by gamer191** [comment]
~~Oops, I completely forgot about this. Anyway, FFmpeg seem to have merged a fix themselves: https://github.com/ffmpeg/ffmpeg/commit/2352145e416c7cbdcf9679ea690c9c1dee4a7936. Can we add that to this repo as a release-only patch?~~

EDIT: nevermind, that patch doesn't fix https://github.com/yt-dlp/yt-dlp/issues/12495

**Comment by gamer191** [comment]
Here's another ffmpeg commit that should be backported to 7.1 (I'll make a PR next time I remember about it lol) https://github.com/FFmpeg/FFmpeg/commit/48c0dba23b3ce8c2bcb180bd2c8029c3c2875424

**Comment by God-damnit-all** [comment]
> Here's another ffmpeg commit that should be backported to 7.1 (I'll make a PR next time I remember about it lol) [FFmpeg/FFmpeg@48c0dba](https://github.com/FFmpeg/FFmpeg/commit/48c0dba23b3ce8c2bcb180bd2c8029c3c2875424)

Don't forget to remember! 😛

**Comment by nihil-admirari** [comment]
Backported https://github.com/FFmpeg/FFmpeg/commit/48c0dba23b3ce8c2bcb180bd2c8029c3c2875424 to 7.1.

**Comment by gamer191** [comment]
> Backported [FFmpeg/FFmpeg@48c0dba](https://github.com/FFmpeg/FFmpeg/commit/48c0dba23b3ce8c2bcb180bd2c8029c3c2875424) to 7.1.

Thanks

Apologies, I forgot to mention that the relevant yt-dlp issue is https://github.com/yt-dlp/yt-dlp/issues/12741. Up to you whether to update the readme (I don't think it's worth me making a PR, given it would cause conflict hell next time the `rebase on upstream` action runs?)

**Comment by lrstanley** [comment]
> If new patches are added, the repository can be resurrected.

> Rather than archiving, it might be better to simply halt the workflows, remove the releases, and say the repo is retired. That way a PR can be submitted for the patches that are welcome, as well as allowing a new issue to be posted if there's something that was overlooked.

I have a library that auto-downloads/installs yt-dlp (paired with cli bindings for that specific version), and I'd like to add ffmpeg capabilities to that list, however, I'd like to pick a source that is going to have updated ffmpeg builds. I'd prefer a solution that has versions of ffmpeg I know should always work with yt-dlp, however, if the plan is to spin up and down the repo based on some patches being needed for some builds, it makes it difficult to have a stable source.

Thoughts on continuing to let workflows/builds/etc run, even when there are no patches, so there is a reliable place to pull binaries from? In the situations where there are no patches, I assume that it would just constantly pull from upstream and no changes would be needed (and thus theoretically, little effort to maintain).

**Comment by kitsumed** [comment]
Im in the same similar situation as @lrstanley . One of my project release CLI also relies on the builds from this repo during packaging.

That said, if you do plan to discontinue it after all issues are merged into the main repo, I could switch to using [BtbN/FFmpeg-Builds](https://github.com/BtbN/FFmpeg-Builds). However, unless we start building them ourselves making packaging longer, we will lose win x32 support (as BtbN does not build for win x32). Which isn't a huge loss, but still worth a mention.

**Comment by pukkandan** [comment]
We could just add note to readme and maybe lock issue tracker while keeping the CI running

**Comment by BoringBoredom** [comment]
imo, the repo should be kept alive, as chances are high it will be needed occasionally in the future. however, can't the workflow be changed to only trigger when there are new commits in https://github.com/BtbN/FFmpeg-Builds/commits/master/? the last commit was 3 weeks ago, but there have been unnecessary daily compilations since then in both repos regardless

**Comment by gamer191** [comment]
@BoringBoredom [btbn/ffmpeg-builds](https://github.com/btbn/ffmpeg-builds) is a tool for compiling [ffmpeg/ffmpeg](https://github.com/ffmpeg/ffmpeg). There should be a new build whenever [ffmpeg/ffmpeg](https://github.com/ffmpeg/ffmpeg)  has changed, which is practically always

**Comment by BoringBoredom** [comment]
> [@BoringBoredom](https://github.com/BoringBoredom) [btbn/ffmpeg-builds](https://github.com/btbn/ffmpeg-builds) is a tool for compiling [ffmpeg/ffmpeg](https://github.com/ffmpeg/ffmpeg). There should be a new build whenever [ffmpeg/ffmpeg](https://github.com/ffmpeg/ffmpeg) has changed, which is practically always

oops, for some reason i assumed btbn's repo is a mirror of the source, nvm

**Comment by gamer191** [comment]
According to the ffmpeg-devel mailing list, version 8.0 will release imminently. I have a few things to note:

Firstly, like multiple commenters here have noted, it's probably best to keep the daily master releases to avoid breaking links and to make it easier to revive this repo if necessary. However, a new release will break the release build links (eg https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1-latest-win64-gpl-7.1.zip will no longer work once the builds are upgraded from 7.1 to 8.0). In my opinion that is a good opportunity to discontinue the release branch builds. If you decided to do that, the benefit would be that you'd no longer have to maintain 2 sets of patch files, and you'd no longer have to maintain patches once they've been merged into FFmpeg master. The rationale is that, if I'm not mistaken, releases other than FFmpeg master are considered outdated and unsupported, so it is expected for them to contain bugs and users should be encouraged to switch to master. Note that it may be worth keeping (unpatched) release builds for 32-bit Windows, because they're disabled in BtbN's repo.

Secondly, according to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes it looks like `.github/README.md` will be prioritised over `README.md`. Moving the README there could be a good way to avoid future rebase conflicts. I believe that would involve a force-push, so let the record reflect that the current commit history is available at https://github.com/yt-dlp/FFmpeg-Builds/commits/b75d89860f6e26e77fe5c9aff01862a3ea30d6db

**Comment by BlackWinnerYoshi** [comment]
FFmpeg 8.0 "Huffman" just released, which I think has [5cd49e1](https://github.com/FFmpeg/FFmpeg/commit/b76053d8bf322b197a9d07bd27bbdad14fd5bc15) merged in to fix [yt-dlp#5874](https://github.com/yt-dlp/yt-dlp/issues/5874) and
[FFmpeg#6389](https://trac.ffmpeg.org/ticket/6389) [Decoding non-standard HEVC in FLV containers].

[Changelog](https://git.ffmpeg.org/gitweb/ffmpeg.git/shortlog/n8.0) [Release Notes](https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/refs/heads/release/8.0:/RELEASE_NOTES)

**Comment by nihil-admirari** [comment]
1. 7.1 release builds have been decommissioned.
2. 8.0 release builds haven't been added.
3. `master` continues to build, but without any custom patches.

**Comment by BlackWinnerYoshi** [comment]
The "Historical Patches" section still says 7.1 though, and perhaps "Release-only patches" should be commented out like it's done with "Patches Applied"

**Comment by nihil-admirari** [comment]
Changed to 8.0.

**Comment by throwaway242685** [comment]
this repository is actually really useful for me since I'm stuck with a Win 7 x86 laptop with bad specs:(

I don't really have any other place to get the latest ffmpeg build in a "official" way except for this repository.

it would be great if you guys decided to keep this repository alive:(

**Comment by nihil-admirari** [comment]
Upstream doesn't support Windows 7 anymore: https://github.com/yt-dlp/FFmpeg-Builds/issues/61. x64 builds stopped working more than a year ago. x86 can stop working at any moment after a dependency update.

**Comment by throwaway242685** [comment]
welp, it stopped working completely for Windows 7 now :(

I get an error saying "SetThreadDescription missing in kernel32.dll" or something like that when trying to run ffmpeg under Windows 7 now.

does anyone know of any repository that provides ffmpeg builds for Windows 7...?

**Comment by DTrombett** [comment]
The [Gyan dev](<https://www.gyan.dev/ffmpeg/builds/>) essential builds are compatible with Windows 7

**Comment by throwaway242685** [comment]
> The [Gyan dev](<https://www.gyan.dev/ffmpeg/builds/>) essential builds are compatible with Windows 7

I just tried that but it seems like they're only x64 builds, so I can't run it. (my laptop is x86) 

I think I'm screwed:(

**Comment by bashonly** [comment]
@throwaway242685 There is someone on the videohelp and MSFN forums building ffmpeg for [Win7 32-bit](https://forum.videohelp.com/threads/414767-ffmpeg-7-0-1-and-Windows-7/page2#post2771491) and [WinXP/Vista](https://msfn.org/board/topic/184368-who-here-has-a-youtube-dl-compile-for-winxp/page/35/#comments). Use at your own risk, of course
